name: _error
timestamp: 1598743756
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1598743704
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5467: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-2699: Menu
  messages:
    system-messages-5095: 'System Messages'
  content:
    system-content-5140: 'Page Content'
  copyright:
    copyright-9862: Copyright
  spacer:
    spacer-5587: Spacer
  branding:
    branding-5216: Branding
  mobile-menu:
    mobile-menu-1798: Mobile-menu
inherit: {  }
