version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1598743704
layout:
  /header/:
    -
      - 'logo-2128 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-9116
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-7864
    -
      - system-content-3278
  /footer/:
    -
      - position-footer
    -
      - 'copyright-1919 40'
      - 'spacer-9895 30'
      - 'branding-4577 30'
  offcanvas:
    -
      - mobile-menu-9343
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
