name: _offline
timestamp: 1598743756
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1598743704
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-8839: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-9124: Menu
  messages:
    system-messages-8229: 'System Messages'
  content:
    system-content-4475: 'Page Content'
  copyright:
    copyright-3684: Copyright
  spacer:
    spacer-2372: Spacer
  branding:
    branding-7653: Branding
  mobile-menu:
    mobile-menu-1950: Mobile-menu
inherit: {  }
