version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1598743704
layout:
  /header/:
    -
      - 'logo-8839 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-9124
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-8229
    -
      - system-content-4475
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3684 40'
      - 'spacer-2372 30'
      - 'branding-7653 30'
  offcanvas:
    -
      - mobile-menu-1950
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
