version: 2
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2_column_-_right
  timestamp: 1598743704
layout:
  /header/:
    -
      - position-position-9889
  /navigation/:
    -
      - position-position-5612
  /container-main/:
    -
      -
        'main 70':
          -
            - position-breadcrumbs
          -
            - system-messages-1771
          -
            - system-content-9713
      -
        'sidebar 30':
          -
            - position-sidebar
  /footer/:
    -
      - position-position-3339
  offcanvas: {  }
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
    subtype: aside
    block:
      fixed: 1
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-position-9889:
    title: The-blog-header
    attributes:
      key: widget-blog-header
  position-position-5612:
    title: The-blog-nav
    attributes:
      key: widget-blog-nav
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-sidebar:
    attributes:
      key: sidebar
  position-position-3339:
    title: The-blog-footer
    attributes:
      key: widget-blog-footer
